"""empty message

Revision ID: 051c8f4b603f
Revises: b17db96bc493
Create Date: 2025-04-11 17:58:45.617089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051c8f4b603f'
down_revision = 'b17db96bc493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trailer', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('trailer')

    # ### end Alembic commands ###
