"""empty message

Revision ID: 2497a797688a
Revises: 2bc479345573
Create Date: 2025-03-24 16:07:22.241907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2497a797688a'
down_revision = '2bc479345573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('quantity_ticket')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_ticket', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
