"""empty message

Revision ID: 30b0e1b228b3
Revises: ea6b6668411f
Create Date: 2025-04-15 12:11:50.086600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b0e1b228b3'
down_revision = 'ea6b6668411f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('qr_code')

    # ### end Alembic commands ###
