"""empty message

Revision ID: 34993943fa11
Revises: 754388ce80dd
Create Date: 2025-03-30 19:11:28.712332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34993943fa11'
down_revision = '754388ce80dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('director')

    # ### end Alembic commands ###
