"""empty message

Revision ID: 5843f1c1949c
Revises: d8c78cf91302
Create Date: 2025-03-29 12:52:34.807284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5843f1c1949c'
down_revision = 'd8c78cf91302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_times', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved_seats', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_times', schema=None) as batch_op:
        batch_op.drop_column('reserved_seats')

    # ### end Alembic commands ###
