"""empty message

Revision ID: 74a094a6eac9
Revises: 34993943fa11
Create Date: 2025-03-30 19:17:22.289903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a094a6eac9'
down_revision = '34993943fa11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('director')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
