"""empty message

<<<<<<<< HEAD:migrations/versions/9e64edccc41d_.py
Revision ID: 9e64edccc41d
Revises: 
Create Date: 2025-03-19 20:23:30.889587
========
Revision ID: 766ef8fcc007
Revises: 
Create Date: 2025-03-19 20:26:28.269562
>>>>>>>> develop:migrations/versions/766ef8fcc007_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766ef8fcc007'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('cinema_col', sa.Integer(), nullable=True),
    sa.Column('cinema_row', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('runtime', sa.Integer(), nullable=False),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('adult', sa.Boolean(), nullable=True),
    sa.Column('backdrop_path', sa.String(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_prince', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('Bebida', 'Comida', 'Merch', name='category'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('wallet', sa.Float(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('show_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('cinema_room_id', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cinema_room_id'], ['cinema_rooms.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('showtime_id', sa.Integer(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=True),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['showtime_id'], ['show_times.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_prince', sa.Float(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_lines')
    op.drop_table('bookings')
    op.drop_table('show_times')
    op.drop_table('sales')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('movies')
    op.drop_table('cinema_rooms')
    # ### end Alembic commands ###
