"""empty message

Revision ID: 80e2bbf7437c
Revises: 051c8f4b603f
Create Date: 2025-04-11 19:48:59.103447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e2bbf7437c'
down_revision = '051c8f4b603f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actors', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('director', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('director')
        batch_op.drop_column('actors')

    # ### end Alembic commands ###
