"""empty message

Revision ID: 91c8ead9cef5
Revises: 5843f1c1949c
Create Date: 2025-03-30 19:41:27.330910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c8ead9cef5'
down_revision = '5843f1c1949c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_times', schema=None) as batch_op:
        batch_op.drop_column('reserved_seats')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_times', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved_seats', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
