"""empty message

Revision ID: dd15e0f746cb
Revises: 2c9f0daf7308
Create Date: 2025-03-18 22:50:18.020249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd15e0f746cb'
down_revision = '2c9f0daf7308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('showtime_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('bookings_showtime_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('bookings_user_id_fkey', type_='foreignkey')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('sales_user_id_fkey', type_='foreignkey')

    with op.batch_alter_table('sales_lines', schema=None) as batch_op:
        batch_op.drop_constraint('sales_lines_product_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_lines_sale_id_fkey', type_='foreignkey')

    with op.batch_alter_table('show_times', schema=None) as batch_op:
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cinema_room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('show_times_cinema_room_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('show_times_movie_id_fkey', type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint('users_username_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_username_key', ['username'])
        batch_op.alter_column('username',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('show_times', schema=None) as batch_op:
        batch_op.create_foreign_key('show_times_movie_id_fkey', 'movies', ['movie_id'], ['id'])
        batch_op.create_foreign_key('show_times_cinema_room_id_fkey', 'cinema_rooms', ['cinema_room_id'], ['id'])
        batch_op.alter_column('cinema_room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sales_lines', schema=None) as batch_op:
        batch_op.create_foreign_key('sales_lines_sale_id_fkey', 'sales', ['sale_id'], ['id'])
        batch_op.create_foreign_key('sales_lines_product_id_fkey', 'products', ['product_id'], ['id'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_foreign_key('sales_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_foreign_key('bookings_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('bookings_showtime_id_fkey', 'show_times', ['showtime_id'], ['id'])
        batch_op.alter_column('showtime_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
