"""empty message

Revision ID: e84ef94312ed
Revises: b4270c92f7fe
Create Date: 2025-04-03 22:35:58.348972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84ef94312ed'
down_revision = 'b4270c92f7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
